// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {liveroom} from '../models';

export function Greet(arg1:string):Promise<string>;

export function LoadFocus():Promise<Array<liveroom.LiveRoomInfo>>;

export function MessageDialog(arg1:string,arg2:string):Promise<void>;

export function SelectFile():Promise<string>;
