// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeQualityFromD2Art(arg1) {
  return window['go']['app']['Server']['ChangeQualityFromD2Art'](arg1);
}

export function GetFocus() {
  return window['go']['app']['Server']['GetFocus']();
}

export function GetLiveRoom(arg1, arg2) {
  return window['go']['app']['Server']['GetLiveRoom'](arg1, arg2);
}

export function GetLiveRoomInfo(arg1, arg2) {
  return window['go']['app']['Server']['GetLiveRoomInfo'](arg1, arg2);
}

export function GetRecommend(arg1, arg2) {
  return window['go']['app']['Server']['GetRecommend'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['app']['Server']['SetContext'](arg1);
}
