// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {liveroom} from '../models';

export function ChangeQualityFromD2Art(arg1:Array<liveroom.Quality>):Promise<Array<liveroom.ArtQuality>>;

export function GetFocus():Promise<Array<liveroom.LiveRoomInfo>>;

export function GetLiveRoom(arg1:string,arg2:string):Promise<liveroom.LiveRoom>;

export function GetLiveRoomInfo(arg1:string,arg2:string):Promise<liveroom.LiveRoomInfo>;

export function GetRecommend(arg1:number,arg2:number):Promise<Array<liveroom.LiveRoomInfo>>;
