// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeQualityFromD2Art(arg1) {
  return window['go']['main']['App']['ChangeQualityFromD2Art'](arg1);
}

export function GetFocus() {
  return window['go']['main']['App']['GetFocus']();
}

export function GetLiveRoom(arg1, arg2) {
  return window['go']['main']['App']['GetLiveRoom'](arg1, arg2);
}

export function GetLiveRoomInfo(arg1, arg2) {
  return window['go']['main']['App']['GetLiveRoomInfo'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadFocus() {
  return window['go']['main']['App']['LoadFocus']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
